### ISSUE TITLE
networks and network names not outputting for cypher output - Oakland database

### ISSUE THREAD

**Issue by azadag** [antievictionmappingproject/worst-evictors-bay-area#8]
We need to take another look at the oakland cypher queries to output data for Oakland...

https://docs.google.com/document/d/1wf7z-CQKr0XglzDIcfjYxqqL_YPgvc1H/edit
there are no network_ids exported from this query:

```
MATCH(n:RB_Eviction) 
WHERE n.evict_date > "20170101"
OPTIONAL MATCH (o:A_Parcel)-[p]-(n)
OPTIONAL MATCH (addr:Parcel_Address)-(n)
OPTIONAL MATCH (n)-[r]-(m:RB_Evictor) 
OPTIONAL MATCH (m)-[:BE_LINKED_TO]-(q)

RETURN o.parcel_id AS block_lot, 
addr.addr AS parc_addr, 
n.evict_id AS evict_id, 
n.evict_date AS evict_date, 
n.type AS evict_type, 
m.evictor AS evictor_name, 
r.evictor_origin AS source_data_evictor,
q.network_id AS evictor_network_id, 
o.network_id AS parc_network_id
```

and no network ids/ names exported from this one

```
MATCH (n:SOS_LP)
RETURN 
n.transaction_date,
n.network_id,
n.name_norm

```

**Comment by dpsgit** [comment]
Regarding the first query -- there looks like there's a missing "-" that I added as a suggested change in the document

However the behavior re: the network_id fields seems to be functional -- the way the Cypher query is written, the network_id will only display if the evictor (i.e. owner at the time of the eviction) is a corporate entity. More broadly, though, we don't assign non-corporate evictors a network_id, since our definition of networks is based on _current_ property ownership, and we don't attempt to create networks from past non-corporate property owners. 

![image](https://user-images.githubusercontent.com/2603366/191129809-a39f0638-585b-4a1a-85bf-8628b132bd67.png)

Re: the 2nd query, I'm not able to reproduce this, it's displaying results for me. 

![image](https://user-images.githubusercontent.com/2603366/191130147-e16bd65d-fc3a-4d0c-90dd-859c7b04b1c8.png)

For reference, I'm using the database dump that is downloaded by the head of `oakland` on the `eb-data-pipeline` repo. Maybe we're looking at different databases?

**Comment by dpsgit** [comment]
Oh also -- I might recommend casting the eviction date to a date timestamp type, instead of relying on alphanumerical ordering for the eviction -- i think with our date format it'll still work, but there might be some weirdness

**Comment by azadag** [comment]
I removed the date cast because it wasn't allowing the query to run at all..

**Comment by azadag** [comment]
ok that's correct about functional design of the query... 

but for me, for the sos and corp there were NO networks connected, and the corp network overloaded mycomputer since it was outputting ALL corps, and not filtering them to ones with transactions...

**Comment by dpsgit** [comment]
It seems like we might be running this on different databases then, if you and I are getting different outputs for the 2nd query. What were you running these Cypher commands on?

**Comment by azadag** [comment]
a locally built database from last week or so, should have been oakland mainline...

**Comment by dpsgit** [comment]
Mm I see, okay looks like the default DB dump hasn't been updated since 6/15/22, so looks like some changes since then have broken the network connections. I can try to take a look into this later this week

**Comment by azadag** [comment]
ok that explains it, so FE is using the 6/15... woof.
